# https://circleci.com/docs/2.0/sample-config/#sample-configuration-with-fan-infan-out-workflow
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get install -y rsync && sudo apt-get install Python-bs4

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # for sync submodules from github
      - add_ssh_keys:
          fingerprints:
            - "1b:b6:ef:e0:fb:85:6d:8f:78:87:a6:ce:1f:34:ec:66"

      - restore_cache:
          keys:
            - submodules-{{ .Environment.CIRCLE_SHA1 }}

      - run: npm run build

      - save_cache:
          key: submodules-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - content

      - save_cache:
          key: dist-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  preview:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo

    steps:
      # notice netlify to deploy preview branch
      # when be triggered by webhook from submodule
      - run: curl -X POST -d '' https://api.netlify.com/build_hooks/5cb97398aed249fc2447b1f1

  deploy:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo

    steps:
      - restore_cache:
          key: dist-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: "Publish to website"
          command: |
            ssh-keyscan "${DEPLOY_HOST}" >> ~/.ssh/known_hosts 2>/dev/null;
            rsync -avz --delete dist/ "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}" || true;
            ssh-keyscan "${DEPLOY_AWS_HOST}" >> ~/.ssh/known_hosts 2>/dev/null;
            rsync -avz --delete dist/ "${DEPLOY_AWS_USER}@${DEPLOY_AWS_HOST}:${DEPLOY_AWS_PATH}" || true;

      # update sitemap
      - run: curl "http://www.google.com/ping?sitemap=https://pingcap.com/sitemap.xml"

      - add_ssh_keys:
          fingerprints:
            - "6a:a6:ac:e8:9e:ee:7d:ef:18:92:94:0b:b0:2c:34:82"

      - run:
          name: "Publish to github.io"
          command: |
            chmod +x ./scripts/push-gh-pages.sh;sh ./scripts/push-gh-pages.sh;

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - preview:
          requires:
            - build
          filters:
            branches:
              only: yini/web-preview
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: src
